### ISSUE TITLE
Stairs are wrong operator

### ISSUE THREAD

**Issue by codemicro** [codemicro/ukvbeta#4]
**Describe the bug**
The stairs have the wrong logo on them, and the logo for FlyUK is upside down.

**Models involved**
Staircase, baggage loader

**Screenshots**
![Link](https://i.gyazo.com/9cb3196997096c0ffca5ce7841d623e4.jpg)

**Desktop (please complete the following information):**
 - Simulator version: unknown
 - Beta version: stable1.3.2
 - Addons in use: unknown

**Comment by martyp187** [comment]
Just checking, this fix will work for the other vehicles with the same issue (as they are linked back to the same logo?)

As I see the same issue on the baggage cart tractor, pushback tugs.

**Comment by codemicro** [comment]
Yeah, the fallbacks all point to the staircase directory, but not the staircase that's shown there. I have a sneaky suspicion that that staircase is new.

**Comment by codemicro** [comment]
I have no idea what caused that staircase thing. Still working on it.

**Comment by codemicro** [comment]
No evidence for this issue continuing. Closed thread.
